### PR TITLE
Merge pull request #6 from umuccmsc/ryan

### PR DESCRIPTION
**Pull request by typecampo**
Ryan

### CODE REVIEW

**Comment by AncarW** [comment]
ryan,

hey this is what I was had setup. Is this something like you had in mind or
no?

**Comment by AncarW** [comment]
I'll have to go through and see if I can't integrate the files you guys
have properly.

**Comment by typecampo** [comment]
You need to stick to the design. We do not need CSS all that is handled with bootstrap. I sent you an email with a link to what the list view should look like. Also the file locations are absolutely important.

Also do a git pull from the master. We already have the add task function. The form is already handled and the data is sent to server already. See the design doc and the phase 1 doc.

**Comment by typecampo** [comment]
@AncarW here look at this https://getbootstrap.com/docs/4.1/content/tables/

**Comment by AncarW** [comment]
hmm yeah i dont know enough about code igniters or php to really get this
going atm.

**Comment by typecampo** [comment]
Ancar just make a skeleton table using this https://getbootstrap.com/docs/4.1/content/tables/

it needs to go into todo.njk

then once Tim completes the data storage function we simply loop over the data and append to the table. In addition, each table entry needs to have an edit and delete button.
https://getbootstrap.com/docs/4.1/components/buttons/

Just do the html markup. Do not worry about how the items get added or removed. I just want to see a single line in the table with a delete and edit button. Thats it.

**Comment by AncarW** [comment]
hey hows this?

**Pull request merged**
